apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-gohelloworld-service-dev
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/my-learning-project-359202/go-demo/gohelloworld:v1